version: '2'
services:
  gff2neo:
    build: .
    environment:
      DB: db
    depends_on:
      - db
  db:
    restart: always
    build: ./neo4j/
    environment:
      NEO4J_AUTH: none
#      Tuning
#      NEO4J_dbms_memory_pagecache_size: 8G
#      NEO4J_dbms_memory_heap_initial__size: 2G
#      NEO4J_dbms_memory_heap_max__size: 2G
    volumes:
      - db_data:/data
    depends_on:
      - es
    ports:
      - "7687:7687"
      - "7474:7474"
  es:
    restart: always
#    image: elasticsearch:2.4
    build: ./es/
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
volumes:
  db_data:
  es_data:

#networks:
#  default:
#    external:
#      name: combattbweb_default
